// app/layout.js
import Layout from './Header/Layout';
import './globals.css';

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
   <Layout>
   {children}

   </Layout>
       
      </body>
    </html>
  );
}
